### ISSUE TITLE
Generated code requires `extern crate protobuf` and `self::protobuf`?

### ISSUE THREAD

**Issue by aaronlevin** [stepancheg/rust-protobuf#291]
Perhaps I'm doing this wrong, but I was getting weird import and modules errors without doing the following to the generated `descriptors.rs` file:

1. adding `extern crate protobuf;`
2. running `sed 's/::protobuf::/self::protobuf::/g'`

My project basically looks like:
```toml
# Cargo.toml
[package]
# ...
build = "build.rs"

[dependencies]
protobuf = { version = "~2.0", features = ["with-bytes"] }

[build-dependencies]
protoc-rust = "2.0"
```

```rust
// build.rs
extern crate protoc_rust;

fn main() {

        protoc_rust::run(protoc_rust::Args {
        out_dir: "src",
        input: &["protos/descriptors.proto"],
        includes: &["protos"],
        customize: protoc_rust::Customize {
            ..Default::default()
        },
    }).expect("protoc");
}
```
```
// src/lib.rs
mod descriptors;
```

The generated `src/descriptors.rs` looks similar to what's in `rust-protobuf`.

Is this intended? If it's not, I would be happy to try and submit a PR. If it is intended, am I setting up my project wrong or doing something weird? 

Thanks! let me know if I can be more clear or anything.
